### ISSUE TITLE
advantages

### ISSUE THREAD

**Issue by cforce** [pencil/redmine_activerecord_session_store#1]
Can u post more info what are the advantages. If its perfoemance what is improves and how much? Didy oyu make any perfoemance test and have regression (former,later) results?

**Comment by RafiGreenberg** [comment]
I am curious about this too. What are the benefits of using this?

**Comment by luxflux** [comment]
Yeah, wondering too. Think the readme needs some more :heart:

**Comment by pencil** [comment]
- Requests are smaller (cookie size decreased in my short tests from about 430 bytes to 32 bytes)
- No magic and vulnerable session secret involved
- Our SSO (CASino) required this for Single Log-out

**Comment by pencil** [comment]
@luxflux Feel free to contribute :wink:

**Comment by cforce** [comment]
I think there is also a redmine issue, can u link it here. Because if this advantages exists ist shall be part of the core
